library(shiny)
library(shinydashboard)
library(RODBC)
library(RSQLServer)
library(ggplot2)
library(dplyr)
library(stringi)
source('~/Documents/Coursera_R/Dashboard/POSIXt2matlabUTC.R')
source('~/Documents/Coursera_R/Dashboard/IUPRQuery.R')
source('~/Documents/Coursera_R/Dashboard/PpK.R')
source('~/Documents/Coursera_R/Dashboard/RYG_Grade.R')
# connect to the server need to be going to global.R at a later stage.
conn <-odbcConnect("Capability")
conn2 <- odbcConnect("IUPR")
PrgMap <- list(Programs = c("Pick Up", "Chasis Cab", "Acadia"), Database = c("Seahawk", "DragonCC","Acadia"))
def_trk <- sqlQuery(conn, paste("select [TruckName] from",PrgMap$Database[[1]],".dbo. tblTrucks"))
DiagList <- sqlQuery(conn, paste("select * from",PrgMap$Database[[1]],".dbo. tblProcessingInfo"))
SoftwareBuild <- sqlQuery(conn,paste("Select distinct calibration from",PrgMap$Database[[1]], " .dbo.tblDataInBuild"))
trucks <- sqlQuery(conn, paste("select * from",PrgMap$Database[[1]],".dbo. tblTrucks"))